runtime: python39
entrypoint: gunicorn -b :$PORT main:app

instance_class: F2

handlers:
- url: /predict
  script: auto

- url: /food-detail/.*
  script: auto

- url: /random-foods
  script: auto

- url: /.*
  static_files: static/\1
  upload: static/.*
